/* Collaborative booking workspace. Independent from Timeline; optionally linked to Guide places. */
(function(root){
  'use strict';
  const KEY=(root.STORAGE_CONFIG&&STORAGE_CONFIG.keys.bookings)||'ccmv_vietnam_bookings_v1';
  const DEFAULTS=[
    {id:'bk-omakase-tiger',placeId:'omakase-tiger',category:'Restaurant',title:'Omakase Tiger',day:'Day 1 · 30 Oct',time:'17:30',partySize:4,status:'confirmed',bookingName:'',confirmation:'Restaurant confirmed availability',contact:'',deposit:'',deadline:'',notes:'',updatedBy:'crystal',updatedAt:''},
    {id:'bk-nha-suga',placeId:'nha-suga',category:'Spa',title:'Spa Nhà Suga Premium',day:'Day 1 · 30 Oct',time:'14:00–17:00',partySize:4,status:'pending',bookingName:'',confirmation:'',contact:'+84 935 227 989',deposit:'',deadline:'',notes:'Confirm treatment duration and arrival time.',updatedBy:'',updatedAt:''},
    {id:'bk-cooking',placeId:'cooking',category:'Activity',title:'Saigon Cooking Class',day:'Day 2 · 31 Oct',time:'10:00–13:00',partySize:4,status:'pending',bookingName:'',confirmation:'',contact:'',deposit:'',deadline:'',notes:'Confirm meeting instructions for 80/1 Nguyễn Trãi.',updatedBy:'',updatedAt:''},
    {id:'bk-moc-kim',placeId:'moc-kim',category:'Spa',title:'Mộc Kim Spa & Beauty',day:'Day 2 · 31 Oct',time:'',partySize:4,status:'pending',bookingName:'',confirmation:'',contact:'',deposit:'',deadline:'',notes:'',updatedBy:'',updatedAt:''},
    {id:'bk-little-bear',placeId:'little-bear',category:'Restaurant',title:'Little Bear',day:'Day 3 · 1 Nov',time:'',partySize:4,status:'pending',bookingName:'',confirmation:'',contact:'+84 862 512 086',deposit:'',deadline:'',notes:'',updatedBy:'',updatedAt:''},
    {id:'bk-moc-huong',placeId:'moc-huong',category:'Spa',title:'Mộc Hương Wellness',day:'Day 3 · 1 Nov',time:'',partySize:4,status:'pending',bookingName:'',confirmation:'',contact:'+84 28 3744 4550',deposit:'',deadline:'',notes:'',updatedBy:'',updatedAt:''},
    {id:'bk-quince',placeId:'quince',category:'Restaurant',title:'Quince Saigon',day:'Day 4 · 2 Nov',time:'',partySize:4,status:'pending',bookingName:'',confirmation:'',contact:'',deposit:'',deadline:'',notes:'Confirm Monday service.',updatedBy:'',updatedAt:''},
    {id:'bk-tinh-thuc',placeId:'tinh-thuc',category:'Spa',title:'Tỉnh Thức Spa',day:'Day 4 · 2 Nov',time:'15:15–17:00',partySize:4,status:'pending',bookingName:'',confirmation:'',contact:'',deposit:'',deadline:'',notes:'Confirm Monday appointment and treatment.',updatedBy:'',updatedAt:''},
    {id:'bk-ha-spa',placeId:'ha-spa',category:'Spa',title:'Hạ Spa',day:'Day 5 · 3 Nov',time:'',partySize:4,status:'pending',bookingName:'',confirmation:'',contact:'',deposit:'',deadline:'',notes:'Confirm timing against airport transfer.',updatedBy:'',updatedAt:''},
    {id:'bk-transfer-in',placeId:null,category:'Transfer',title:'Airport transfer · Arrival',day:'Day 1 · 30 Oct',time:'06:00',partySize:4,status:'confirmed',bookingName:'',confirmation:'Klook transfer',contact:'',deposit:'',deadline:'',notes:'SGN → Fusion Original.',updatedBy:'crystal',updatedAt:''},
    {id:'bk-transfer-out',placeId:null,category:'Transfer',title:'Airport transfer · Departure',day:'Day 5 · 3 Nov',time:'',partySize:4,status:'pending',bookingName:'',confirmation:'',contact:'',deposit:'',deadline:'',notes:'Fusion Original → SGN.',updatedBy:'',updatedAt:''}
  ];
  function clone(v){return JSON.parse(JSON.stringify(v));}
  function load(){const saved=STORAGE.local.readJSON(KEY,null); if(!Array.isArray(saved)){STORAGE.local.writeJSON(KEY,clone(DEFAULTS));return clone(DEFAULTS);} const byId=new Map(saved.map(x=>[x.id,x])); DEFAULTS.forEach(x=>{if(!byId.has(x.id))saved.push(clone(x));}); return saved;}
  function save(rows){STORAGE.local.writeJSON(KEY,rows); window.dispatchEvent(new CustomEvent('ccmv:bookings-changed'));}
  function label(status){return status==='confirmed'?'✓ Confirmed':status==='cancelled'?'Cancelled / unavailable':'Pending';}
  function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
  function user(){try{return getFriend();}catch(e){return STORAGE.local.get(STORAGE_CONFIG.keys.friend,'crystal');}}
  function person(k){return (root.VN_PRESENTATION?.friends||{})[k]||k||'—';}
  function summary(rows){const c=rows.filter(x=>x.status==='confirmed').length,p=rows.filter(x=>x.status==='pending').length,u=rows.filter(x=>x.status==='cancelled').length;return `${c} Confirmed · ${p} Pending${u?` · ${u} Unavailable`:''}`;}
  function render(){const host=document.getElementById('bookingList');if(!host)return;const rows=load(); const sum=document.getElementById('bookingSummary');if(sum)sum.textContent=summary(rows); const cats=['Restaurant','Spa','Activity','Transfer']; host.innerHTML=cats.map(cat=>{const group=rows.filter(x=>x.category===cat);if(!group.length)return'';return `<section class="booking-group"><h2>${cat==='Restaurant'?'🍽':cat==='Spa'?'💆':cat==='Activity'?'🎫':'🚐'} ${cat}${cat==='Activity'?'ies':'s'}</h2>${group.map(card).join('')}</section>`}).join('');}
  function card(b){const meta=[b.day,b.time,b.partySize?`${b.partySize} guests`:null].filter(Boolean).join(' · ');return `<article class="booking-card ${b.status}"><button type="button" class="booking-card-main" onclick="openBookingEditor('${esc(b.id)}')"><span><strong>${esc(b.title)}</strong><small>${esc(meta)}</small></span><span class="booking-status ${b.status}">${label(b.status)}</span></button>${b.updatedBy?`<p class="booking-updated">Last updated by ${esc(person(b.updatedBy))}${b.updatedAt?` · ${new Date(b.updatedAt).toLocaleString()}`:''}</p>`:''}</article>`;}
  root.openBookingEditor=function(id){const b=load().find(x=>x.id===id);if(!b)return; const modal=document.getElementById('bookingModal'),host=document.getElementById('bookingEditor');host.innerHTML=`<p class="kicker">Shared booking</p><h2>${esc(b.title)}</h2><p class="booking-place-link">${b.placeId?`<a href="place.html?place=${encodeURIComponent(b.placeId)}">Open Guide card →</a>`:'Independent booking record'}</p><form onsubmit="saveBookingEditor(event,'${esc(id)}')"><label>Status<select name="status"><option value="pending" ${b.status==='pending'?'selected':''}>Pending</option><option value="confirmed" ${b.status==='confirmed'?'selected':''}>Confirmed</option><option value="cancelled" ${b.status==='cancelled'?'selected':''}>Cancelled / unavailable</option></select></label><div class="booking-two"><label>Date / day<input name="day" value="${esc(b.day)}"></label><label>Time<input name="time" value="${esc(b.time)}"></label></div><div class="booking-two"><label>Guests<input name="partySize" type="number" min="1" value="${esc(b.partySize)}"></label><label>Booking name<input name="bookingName" value="${esc(b.bookingName)}"></label></div><label>Confirmation / reference<input name="confirmation" value="${esc(b.confirmation)}"></label><label>Contact / WhatsApp / phone<input name="contact" value="${esc(b.contact)}"></label><div class="booking-two"><label>Deposit<input name="deposit" value="${esc(b.deposit)}"></label><label>Cancellation deadline<input name="deadline" value="${esc(b.deadline)}"></label></div><label>Notes<textarea name="notes">${esc(b.notes)}</textarea></label><button class="btn" type="submit">Save booking details</button></form>`;modal.classList.add('show');};
  root.closeBookingModal=function(){document.getElementById('bookingModal')?.classList.remove('show');};
  root.saveBookingEditor=function(ev,id){ev.preventDefault();const f=new FormData(ev.currentTarget),rows=load(),b=rows.find(x=>x.id===id);if(!b)return;b.status=f.get('status');['day','time','bookingName','confirmation','contact','deposit','deadline','notes'].forEach(k=>b[k]=String(f.get(k)||''));b.partySize=Number(f.get('partySize'))||4;b.updatedBy=user();b.updatedAt=new Date().toISOString();save(rows);closeBookingModal();render();};
  root.CCMV_BOOKINGS=Object.freeze({getAll:load,getForPlace(placeId){return load().filter(x=>x.placeId===placeId);},label});
  document.addEventListener('DOMContentLoaded',render);window.addEventListener('storage',e=>{if(e.key===KEY)render();});window.addEventListener('ccmv:bookings-changed',render);
})(globalThis);
