/* Vietnam Export Centre. Reads existing production authorities only. */
(function(root){'use strict';
 const read=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch(e){return f}};
 const esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
 function print(title,body){const w=open('','_blank');if(!w)return alert('Please allow pop-ups for export.');w.document.write(`<!doctype html><meta charset=utf-8><title>${esc(title)}</title><style>body{font:14px Arial;padding:28px;color:#2d241f}h1,h2{color:#7b432a}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid #ddd;padding:8px;text-align:left}@media print{button{display:none}}</style><button onclick="print()">Print / Save PDF</button><h1>${esc(title)}</h1>${body}`);w.document.close();}
 function expense(){const a=read('expenses');const s=root.CCMV_EXPENSE_CALC?.summarise(a);print('CCMV Saigon — Expense Export',`<h2>Trip Total: ${(s?.total||0).toLocaleString()} VND</h2><table><tr><th>Item</th><th>Total</th><th>Paid by</th><th>Allocation</th></tr>${a.map(e=>`<tr><td>${esc(e.item)}</td><td>${Number(e.total||0).toLocaleString()} VND</td><td>${esc(e.paidBy)}</td><td>${esc(JSON.stringify(root.CCMV_EXPENSE_CALC?.allocations(e)||{}))}</td></tr>`).join('')}</table>`)}
 function settlement(){const s=root.CCMV_EXPENSE_CALC?.summarise(read('expenses'));print('CCMV Saigon — Settlement',`<table>${Object.entries(s?.balance||{}).map(([k,v])=>`<tr><th>${esc(k)}</th><td>${v>=0?'Receive':'Owes'} ${Math.abs(Math.round(v)).toLocaleString()} VND</td></tr>`).join('')}</table>`)}
 function memory(){const a=read('moments_list');print('CCMV Saigon — Memory Export',a.length?a.map(m=>`<article><h2>${esc(m.displayTitleSnapshot||m.title||'Moment')}</h2><p>${esc(m.friend||m.partyId||'')}</p><p>${esc(m.text||m.note||'')}</p></article>`).join(''):'<p>No moments yet.</p>')}
 function itinerary(){const d=root.VN_PRESENTATION?.itineraryData||{};print('CCMV Saigon — Itinerary Export',Object.entries(d).map(([n,day])=>`<h2>Day ${n} · ${esc(day.title||'')}</h2>${(day.items||[]).map(i=>`<p><strong>${esc(i.time||'')}</strong> ${esc(i.title||'')}</p>`).join('')}`).join(''))}
 function openCentre(){let m=document.getElementById('ccmvExportCentre');if(!m){m=document.createElement('div');m.id='ccmvExportCentre';m.className='ccmv-cap-modal';m.innerHTML=`<div><button class="x">×</button><p class="kicker">EXPORT CENTRE</p><h2>Vietnam Exports</h2><button data-e="itinerary">Itinerary PDF</button><button data-e="expense">Expense PDF</button><button data-e="settlement">Settlement</button><button data-e="memory">Memory</button></div>`;document.body.appendChild(m);m.onclick=e=>{if(e.target.classList.contains('x'))m.classList.remove('show');const x=e.target.dataset.e;if(x==='itinerary')itinerary();if(x==='expense')expense();if(x==='settlement')settlement();if(x==='memory')memory();}}m.classList.add('show')}
 root.CCMV_EXPORT_CENTRE=Object.freeze({open:openCentre,itinerary,expense,settlement,memory});
})(globalThis);
