/* Vietnam production Admin/Studio shell — Crystal only. */
(function(root){'use strict';
 const K={mode:'ccmv-vn:admin:mode',draft:'ccmv-vn:admin:draft',pin:'ccmv-vn:admin:pin'};let baseline=null,dirty=false,suppress=false;
 const friend=()=>{try{return root.getFriend?.()||localStorage.getItem('saigon_friend')||'crystal'}catch(e){return 'crystal'}};
 const snap=()=>{const o={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&!k.startsWith('ccmv-vn:admin:'))o[k]=localStorage.getItem(k)}return o};
 function restore(s){suppress=true;const keep=new Set(Object.keys(s||{}));for(let i=localStorage.length-1;i>=0;i--){const k=localStorage.key(i);if(k&&!k.startsWith('ccmv-vn:admin:')&&!keep.has(k))localStorage.removeItem(k)}Object.entries(s||{}).forEach(([k,v])=>localStorage.setItem(k,v));suppress=false}
 function hash(v){let h=2166136261;for(const c of String(v))h=Math.imul(h^c.charCodeAt(0),16777619);return(h>>>0).toString(36)}
 const mode=()=>sessionStorage.getItem(K.mode)||'read';
 function enter(){if(friend()!=='crystal')return alert('Trip Studio is available to Crystal only.');const saved=localStorage.getItem(K.pin),p=prompt(saved?'Enter 6-digit Admin PIN':'Create a 6-digit Admin PIN');if(!/^\d{6}$/.test(p||''))return alert('PIN must be 6 digits.');if(saved&&saved!==hash(p))return alert('Incorrect PIN.');if(!saved)localStorage.setItem(K.pin,hash(p));baseline=snap();dirty=false;sessionStorage.setItem(K.mode,'studio');render()}
 function save(){baseline=snap();dirty=false;localStorage.removeItem(K.draft);render()}
 function discard(){if(!confirm('Discard all pending changes?'))return;if(baseline)restore(baseline);dirty=false;localStorage.removeItem(K.draft);location.reload()}
 function exit(){if(dirty&&!confirm('Discard unsaved changes and return to Read Mode?'))return;if(dirty&&baseline)restore(baseline);dirty=false;sessionStorage.setItem(K.mode,'read');render()}
 function mark(){if(suppress||mode()!=='studio')return;dirty=true;localStorage.setItem(K.draft,JSON.stringify({at:new Date().toISOString()}));render()}
 function render(){let bar=document.getElementById('ccmvAdminBar');if(friend()!=='crystal'){bar?.remove();return}if(!bar){bar=document.createElement('div');bar.id='ccmvAdminBar';document.body.appendChild(bar)}const m=mode();document.body.dataset.adminMode=m;bar.innerHTML=m==='studio'?`<strong>Studio Mode</strong><span>${dirty?'Pending Save':'Saved'}</span><button data-a="save" ${dirty?'':'disabled'}>Save</button><button data-a="discard" ${dirty?'':'disabled'}>Discard</button><button data-a="exit">Read</button><button data-a="export">Export</button>`:`<strong>Read Mode</strong><span>Crystal Admin</span><button data-a="enter">Trip Studio</button><button data-a="export">Export Centre</button>`;bar.onclick=e=>{const a=e.target.dataset.a;if(a==='enter')enter();if(a==='save')save();if(a==='discard')discard();if(a==='exit')exit();if(a==='export')root.CCMV_EXPORT_CENTRE?.open()}}
 const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){original.call(this,k,v);if(this===localStorage&&!String(k).startsWith('ccmv-vn:admin:'))queueMicrotask(mark)};
 addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});document.addEventListener('DOMContentLoaded',render);document.addEventListener('click',e=>{if(e.target.closest('[data-action="friend-select"]'))setTimeout(render,50)});setTimeout(render,0);
 root.CCMV_ADMIN=Object.freeze({mode,markDirty:mark,isAdmin:()=>friend()==='crystal'});
})(globalThis);