/* Vietnam production Admin/Studio shell — Crystal only. Selector entry + NZ-reference workspace. */
(function(root){'use strict';
 const K={mode:'ccmv-vn:admin:mode',draft:'ccmv-vn:admin:draft',pin:'ccmv-vn:admin:pin'};
 const DEFAULT_PIN='260922';
 let baseline=null,dirty=false,suppress=false;
 const friend=()=>{try{return root.getFriend?.()||localStorage.getItem('saigon_friend')||'crystal'}catch(e){return 'crystal'}};
 const snap=()=>{const o={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&!k.startsWith('ccmv-vn:admin:'))o[k]=localStorage.getItem(k)}return o};
 function restore(s){suppress=true;const keep=new Set(Object.keys(s||{}));for(let i=localStorage.length-1;i>=0;i--){const k=localStorage.key(i);if(k&&!k.startsWith('ccmv-vn:admin:')&&!keep.has(k))localStorage.removeItem(k)}Object.entries(s||{}).forEach(([k,v])=>localStorage.setItem(k,v));suppress=false}
 function hash(v){let h=2166136261;for(const c of String(v))h=Math.imul(h^c.charCodeAt(0),16777619);return(h>>>0).toString(36)}
 const mode=()=>sessionStorage.getItem(K.mode)||'read';
 function ensurePin(){localStorage.setItem(K.pin,hash(DEFAULT_PIN))}
 function requestPin(){ensurePin();const p=prompt('Enter 6-digit Admin PIN');if(p===null)return false;if(!/^\d{6}$/.test(p))return alert('PIN must be 6 digits.'),false;if(localStorage.getItem(K.pin)!==hash(p))return alert('Incorrect PIN.'),false;return true}
 function enter(){if(friend()!=='crystal')return alert('Trip Studio is available to Crystal only.');if(!requestPin())return;baseline=snap();dirty=false;sessionStorage.setItem(K.mode,'studio');render();openStudio()}
 function save(){baseline=snap();dirty=false;localStorage.removeItem(K.draft);renderStudio();}
 function discard(){if(!confirm('Discard all pending changes?'))return;if(baseline)restore(baseline);dirty=false;localStorage.removeItem(K.draft);location.reload()}
 function exit(){if(dirty&&!confirm('Discard unsaved changes and return to Read Mode?'))return;if(dirty&&baseline)restore(baseline);dirty=false;sessionStorage.setItem(K.mode,'read');closeStudio();render()}
 function mark(){if(suppress||mode()!=='studio')return;dirty=true;localStorage.setItem(K.draft,JSON.stringify({at:new Date().toISOString()}));renderStudio()}
 function injectSelectorEntry(){document.querySelectorAll('.friend-choice-list').forEach(list=>{if(list.querySelector('[data-action="open-trip-studio"]'))return;const divider=document.createElement('div');divider.className='studio-selector-divider';divider.textContent='CREATOR WORKSPACE';const b=document.createElement('button');b.type='button';b.dataset.action='open-trip-studio';b.className='studio-selector-button';b.innerHTML='<span class="studio-selector-icon">✦</span><span><strong>Trip Studio</strong><small>Crystal only</small></span><span class="studio-selector-chevron">›</span>';list.append(divider,b)});}
 function ensureModal(){let m=document.getElementById('ccmvStudioModal');if(m)return m;m=document.createElement('div');m.id='ccmvStudioModal';m.className='ccmv-studio-modal';m.innerHTML='<div class="ccmv-studio-shell"><div class="ccmv-studio-card"><header><div><p>CREATOR WORKSPACE</p><h2>Trip Studio</h2><span>Create, refine and manage this companion.</span></div><button type="button" data-studio="close">×</button></header><section class="studio-mode-row"><div><h3>Studio Mode</h3><p>Turn on editing tools for itinerary and trip data.</p></div><label class="studio-switch"><input type="checkbox" data-studio="toggle"><span></span></label></section><section class="studio-management"><p class="studio-section-label">TRIP MANAGEMENT</p><div class="studio-status-card"><div><h3 data-studio-status>Read Mode</h3><p data-studio-copy>Editing tools are off.</p></div><span data-studio-indicator>○</span></div><div class="studio-actions"><button type="button" data-studio="save">Save</button><button type="button" data-studio="discard">Discard</button></div></section><section><p class="studio-section-label">EXPORT CENTRE</p><button class="studio-export-card" type="button" data-studio="export"><span><strong>Open Export Centre</strong><small>Itinerary, expenses, settlement and memory.</small></span><b>›</b></button></section></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m||e.target.dataset.studio==='close')closeStudio();const a=e.target.closest('[data-studio]')?.dataset.studio;if(a==='toggle'){e.preventDefault();mode()==='studio'?exit():enter()}if(a==='save')save();if(a==='discard')discard();if(a==='export')root.CCMV_EXPORT_CENTRE?.open()});return m}
 function renderStudio(){const m=ensureModal(),studio=mode()==='studio';const toggle=m.querySelector('[data-studio="toggle"]');if(toggle)toggle.checked=studio;const title=m.querySelector('[data-studio-status]'),copy=m.querySelector('[data-studio-copy]'),indicator=m.querySelector('[data-studio-indicator]');if(title)title.textContent=studio?(dirty?'Pending Save':'Studio Mode'):'Read Mode';if(copy)copy.textContent=studio?(dirty?'Changes are waiting to be saved.':'Editing tools are active.'):'Editing tools are off.';if(indicator)indicator.textContent=studio?(dirty?'!':'✓'):'○';m.querySelector('[data-studio="save"]')?.toggleAttribute('disabled',!studio||!dirty);m.querySelector('[data-studio="discard"]')?.toggleAttribute('disabled',!studio||!dirty);}
 function openStudio(){if(friend()!=='crystal')return alert('Trip Studio is available to Crystal only.');document.querySelectorAll('[data-action="friend-close"]').forEach(b=>b.click());const m=ensureModal();renderStudio();m.classList.add('show');document.body.classList.add('studio-open')}
 function closeStudio(){document.getElementById('ccmvStudioModal')?.classList.remove('show');document.body.classList.remove('studio-open')}
 function render(){document.getElementById('ccmvAdminBar')?.remove();injectSelectorEntry();renderStudio()}
 const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){original.call(this,k,v);if(this===localStorage&&!String(k).startsWith('ccmv-vn:admin:'))queueMicrotask(mark)};
 addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
 document.addEventListener('DOMContentLoaded',render);
 document.addEventListener('click',e=>{if(e.target.closest('[data-action="friend-open"]'))setTimeout(injectSelectorEntry,20);if(e.target.closest('[data-action="open-trip-studio"]'))openStudio();if(e.target.closest('[data-action="friend-select"]'))setTimeout(render,50)});
 setTimeout(render,0);
 root.CCMV_ADMIN=Object.freeze({mode,markDirty:mark,isAdmin:()=>friend()==='crystal',open:openStudio});
})(globalThis);
