/* Vietnam Companion — NZ Stage 3.2H Export Centre production port. */
(function(){
 'use strict';
 const ADMIN_USER='crystal';
 function isExportAdmin(){return typeof getFriend==='function'&&getFriend()===ADMIN_USER&&typeof window.isAdminMode==='function'&&window.isAdminMode();}
 function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
 function itinerary(){try{return typeof ITINERARY_DATA!=='undefined'?ITINERARY_DATA:{}}catch(e){return {}}}
 function returnToStudio(){closeTripExportCenter();if(typeof window.openTripStudioPanel==='function')window.openTripStudioPanel();else if(typeof window.openFriendModal==='function')window.openFriendModal();}
 function buildControl(){const host=document.getElementById('tripStudioExports');if(!host||document.getElementById('tripExportControl'))return;const section=document.createElement('section');section.id='tripExportControl';section.className='trip-export-control';section.innerHTML='<button class="trip-export-launch" type="button" onclick="openTripExportCenter()"><span><strong>Open Export Centre</strong><small>Itinerary and expenses are available anytime.</small></span><span aria-hidden="true">›</span></button>';host.appendChild(section);}
 function buildModal(){if(document.getElementById('tripExportModal'))return;const modal=document.createElement('div');modal.id='tripExportModal';modal.className='trip-export-modal';modal.setAttribute('aria-hidden','true');modal.innerHTML=`<div class="trip-export-sheet" role="dialog" aria-modal="true" aria-labelledby="tripExportTitle"><button class="trip-export-close" type="button" onclick="closeTripExportCenter()" aria-label="Close">×</button><p class="kicker">TRIP OUTPUTS</p><h2 id="tripExportTitle">Export Trip</h2><p class="lead">Share the itinerary, create a printable copy, or export the expense record.</p><div class="trip-export-list"><button type="button" onclick="shareItineraryNative()"><span class="trip-export-icon">📤</span><span><strong>Share Itinerary</strong><small>Open WhatsApp, Mail, Messages, AirDrop and other apps.</small></span><span>›</span></button><button type="button" onclick="exportFinalItinerary()"><span class="trip-export-icon">📄</span><span><strong>Printable Itinerary</strong><small>Open a clean copy and save it as PDF.</small></span><span>›</span></button><button type="button" onclick="exportExpenseSummary()"><span class="trip-export-icon">💰</span><span><strong>Expense Summary</strong><small>Download the complete expense and settlement CSV.</small></span><span>›</span></button><button type="button" class="coming-soon" disabled><span class="trip-export-icon">📖</span><span><strong>Memory Book</strong><small>Coming Soon</small></span></button></div></div>`;modal.addEventListener('click',e=>{if(e.target===modal)closeTripExportCenter()});document.body.appendChild(modal);}
 function render(){buildControl();buildModal();const c=document.getElementById('tripExportControl');if(c)c.hidden=!isExportAdmin();if(!isExportAdmin())closeTripExportCenter();}
 window.openTripExportCenter=function(){if(!isExportAdmin())return alert('Enter Studio Mode to export the trip.');if(typeof closeFriendModal==='function')closeFriendModal();buildModal();const m=document.getElementById('tripExportModal');m.classList.add('open');m.setAttribute('aria-hidden','false')};
 window.closeTripExportCenter=function(){const m=document.getElementById('tripExportModal');if(!m)return;m.classList.remove('open');m.setAttribute('aria-hidden','true')};
 window.exportExpenseSummary=function(){if(!isExportAdmin())return alert('Enter Studio Mode to export the trip.');if(typeof window.exportExpenseData!=='function')return alert('Expense export is not available.');window.exportExpenseData();returnToStudio()};
 function shareText(){const src=itinerary(),lines=[];Object.keys(src).sort((a,b)=>+a-+b).forEach(n=>{const d=src[n]||{};lines.push(`${d.kicker||'Day '+n} — ${d.heading||d.title||''}`);(d.items||[]).forEach(i=>{lines.push(`${i.time?i.time+' ':''}${i.title||''}`.trim());(i.details||[]).forEach(x=>lines.push('  '+x))});lines.push('')});return lines.join('\n').trim()}
 window.shareItineraryNative=async function(){if(!isExportAdmin())return alert('Enter Studio Mode to share the trip.');const text=shareText();if(!text)return alert('No itinerary data is available.');const title=(window.TRIP_CONFIG&&TRIP_CONFIG.tripName)||'Saigon Itinerary';try{if(navigator.share){await navigator.share({title,text});closeTripExportCenter();return}if(navigator.clipboard){await navigator.clipboard.writeText(text);alert('Itinerary copied.');closeTripExportCenter();return}}catch(e){if(e&&e.name==='AbortError')return}alert('Sharing is not available right now. Use Printable Itinerary instead.')};
 window.exportFinalItinerary=function(){if(!isExportAdmin())return alert('Enter Studio Mode to export the trip.');const src=itinerary(),days=Object.keys(src).sort((a,b)=>+a-+b);if(!days.length)return alert('No itinerary data is available.');const title=(window.TRIP_CONFIG&&TRIP_CONFIG.tripName)||'Saigon Itinerary';const html=days.map(n=>{const d=src[n]||{};return `<section class="day"><header><p>${esc(d.kicker||'Day '+n)}</p><h2>${esc(d.heading||d.title||'')}</h2></header>${(d.items||[]).map(i=>`<article><div class="time">${esc(i.time||'')}</div><div><h3>${esc(i.title||'')}</h3>${(i.details||[]).map(x=>`<p>${esc(x)}</p>`).join('')}</div></article>`).join('')}</section>`}).join('');const pop=window.open('','_blank');if(!pop)return alert('Please allow pop-ups.');pop.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>@page{size:A4;margin:11mm}*{box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#2b251f;margin:0}.toolbar{position:sticky;top:0;padding:10px;text-align:center;background:#f5eee5}.toolbar button{padding:9px 14px;border-radius:999px;border:1px solid #ccb69f;background:#fff}main{max-width:820px;margin:auto;padding:18px}.day{break-before:page}.day:first-child{break-before:auto}article{display:grid;grid-template-columns:82px 1fr;gap:10px;padding:8px 0;border-bottom:1px solid #eadfd3;break-inside:avoid}.time{font-weight:700;color:#8a4f2d}h2,h3,p{margin:0 0 5px}@media print{.toolbar{display:none}}</style></head><body><div class="toolbar"><button onclick="window.print()">Save as PDF</button></div><main><h1>${esc(title)}</h1>${html}</main></body></html>`);pop.document.close();returnToStudio()};
 document.addEventListener('DOMContentLoaded',render);document.addEventListener('travelengine:adminmodechange',render);document.addEventListener('travelengine:friendchange',render);
})();
